const nextConfig = {
    images: {
        domains: [
            'www.partsgopher.com',
            'res.cloudinary.com',
            'cdn3.volusion.com',
            'nriparts.com',
            'plainongroup-com.1crmcloud.com',
            'cdn.nexternal.com',
            'tsi.com',
            'www.agspray.com',
            'hallbrookcomponents.com',
            'www.newmantools.com',
            'http2.mlstatic.com',
            'www.instrumart.com',
            'www.lovatoelectric.com',
            'i.ebayimg.com',
            'assets.alliedelec.com',
            'www.pccomposites.com',
            'sc04.alicdn.com',
            's1.kaercher-media.com',
            'www.applied-motion.com',
            'concorde-electronics.com',
            'rexel-cdn.com',
            'www.allworldmachinery.com',
            'www.riego-agricola.com',
            'industrialsewingmachineman.com',
            'wilson-company.com',
            'm.media-amazon.com',
            'i0.wp.com',
            'bdsparts.com',
            'ae01.alicdn.com',
            'euroelectrica.com',
            'www.travers.com',
            'shop.gracoroberts.com',
            'www.mouser.com',
            'www.plchardware.com',
            'mundoriego.es',
            'nriparts.com.imgeng.in',
            'euroelectrica.com.mx'
        ],
    },
}

module.exports = nextConfig